### DISCUSSION TITLE
[docker] mysql with exist database

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#16] [DevOps]
```
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./init_db/db_1.sql:/docker-entrypoint-initdb.d/db_1.sql
    ports:
      - 3306:3306
```
