### DISCUSSION TITLE
[mongo] [ubuntu] 20.04 - install

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#175] [Vault]
[https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-20-04](https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-20-04)
[https://www.digitalocean.com/community/tutorials/how-to-secure-mongodb-on-ubuntu-20-04](https://www.digitalocean.com/community/tutorials/how-to-secure-mongodb-on-ubuntu-20-04)
[https://www.digitalocean.com/community/tutorials/how-to-configure-remote-access-for-mongodb-on-ubuntu-20-04](https://www.digitalocean.com/community/tutorials/how-to-configure-remote-access-for-mongodb-on-ubuntu-20-04)
[https://snapshooter.com/learn/mongodb/mongo_replication](https://snapshooter.com/learn/mongodb/mongo_replication)

```
curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
apt-key list
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
sudo apt update
sudo apt install mongodb-org -y


sudo systemctl start mongod.service
sudo systemctl status mongod
sudo systemctl enable mongod

# test database connect
mongo --eval 'db.runCommand({ connectionStatus: 1 })'
```

---
## adding an administrative user
```
mongo
show dbs
use admin

db.createUser(
	{
		user: "odapi",
		pwd: passwordPrompt(),
		roles: [ { role: "userAdminAnyDatabase", db: "admin" }, "readWriteAnyDatabase" ]
	}
)

exit
```

## enabling authentication
```
sudo vi /etc/mongod.conf
```
### change
```
#security:

#operationProfiling:
```
### to
```
security:
  authorization: enabled
```
```
sudo systemctl restart mongod
sudo systemctl status mongod
```

## test
```
mongo -u odapi -p --authenticationDatabase admin
#MGOD190922

```

---
## remote accesss
```
checking which port

sudo vi /etc/mongod.conf
```
### change
```
# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1
```
### to
```
# network interfaces, aws ec2: private ip
net:
  port: 27017
  bindIp: 127.0.0.1,172.31.93.56
```
```
sudo systemctl restart mongod
```

---
## convert a Standalone to a Replica Set
```
sudo su
openssl rand -base64 756 > /opt/mongo-keyfile 
chmod 400 /opt/mongo-keyfile 
chown mongodb:mongodb /opt/mongo-keyfile
sudo chown -R mongodb:mongodb /var/lib/mongodb/*
```

## clear log
```
cat /dev/null > /var/log/mongodb/mongod.log
```

## disable security and create Admin User
```
db.createUser({user: "mongo-admin", pwd: "password", roles:[{role: "root", db: "admin"}]})
```

```
sudo vi /etc/mongod.conf
```
### use private ip
```
# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1,172.31.93.56


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

security:
  authorization: enabled
  keyFile: /opt/mongo-keyfile
#operationProfiling:

replication:
  replSetName: "rs0"
```
  
```
systemctl restart mongod
mongo -u mongo-admin -p --authenticationDatabase admin

> rs.initiate()

exit
```

```
mongo -u mongo-admin -p --authenticationDatabase admin
# mongo -u mongo-admin -p password --authenticationDatabase admin
# use public ip
rs.reconfig({
	"_id" : "rs0",
	"version" : 1,
	"members" : [
		{
			"_id" : 0,
			"host" : "54.208.17.117:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	]
}
, {force: true})
```
