### DISCUSSION TITLE
[nginx] forward nginx incoming request to docker container port

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#200] [DevOps]
docker-compose.yml

```yml
version: '3.7'

services:
  ...
  webserver:
    image: nginx:1.16
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
   ...
```

```
server {
    listen 80;

    server_name example.com;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        proxy_pass http://localhost:8080/;
    }
}
```

for subfolder
```
location /apps/one/client/ {
    proxy_pass http://localhost:3041/;
}
```
