### DISCUSSION TITLE
serverless recursive ( self invoke )

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#201] [Vault]
[REF](https://github.com/serverless/examples/tree/v3/aws-node-recursive-function)

serverless.yml
```
service: recursive-invocation-example

custom:
  functionARN: yourFunctionARN

provider:
  name: aws
  runtime: nodejs12.x
#  iam:
#    role:
#      statements:
#        -  Effect: "Allow"
#           Action:
#             - "lambda:InvokeFunction"
#           Resource: ${self:custom.functionARN}

functions:
  recursiveExample:
    handler: handler.recursiveLambda
```

handler.js
```nodejs
/* eslint-disable */
/* aws-sdk automatically included in lambda context */
const aws = require('aws-sdk');

module.exports.recursiveLambda = (event, context, callback) => {
  const lambda = new aws.Lambda();
  console.log('received', event);
  /* if numberOfCalls still has value, continue recursive operation */
  if (event.numberOfCalls > 0) {
    console.log('recursive call');
    /* decrement numberOfCalls so we don't infinitely loop */
    event.numberOfCalls = event.numberOfCalls - 1;
    const params = {
      FunctionName: context.functionName,
      InvocationType: 'Event',
      Payload: JSON.stringify(event),
      Qualifier: context.functionVersion
    };
    lambda.invoke(params, context.done);
  } else {
    console.log('recursive call finished');
    context.succeed('finished');
  }
};
```

steps:
- sls deploy
- update serverless.yml
```
custom:
  functionARN: arn:aws:lambda:us-east-1:488110005556:function:recursive-invocation-example-dev-recursiveExample

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        -  Effect: "Allow"
           Action:
             - "lambda:InvokeFunction"
           Resource: ${self:custom.functionARN}
```
