### DISCUSSION TITLE
Basic Authentication

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#248] [DevOps]
- [https://viblo.asia/p/basic-authentication-Qbq5QmJL5D8](https://viblo.asia/p/basic-authentication-Qbq5QmJL5D8)
- [https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)

```
Authorization: Basic <Base 64 endcode {username:password}>
```

**Comment by mediumhust** [comment]
[Restricting access with Nginx and basic authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#restricting_access_with_nginx_and_basic_authentication)

```
location /status {
    auth_basic           "Access to the staging site";
    auth_basic_user_file /etc/apache2/.htpasswd;
}
```

**Comment by mediumhust** [comment]
```
sudo htpasswd -c .htpasswd user1
```
docker compose
```
version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    command: nginx -g "daemon off;"
    ports:
      - "8080:80"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./default.conf:/etc/nginx/conf.d/default.conf
```
default.conf
```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name localhost;

    location / {
        try_files $uri $uri/ =404;
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}
```
