### DISCUSSION TITLE
minikube local image

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#272] [DevOps]
1 - Set the environment variables with `eval $(minikube docker-env)`
2 - Build the image with the Docker daemon of Minikube (eg `docker build -t my-image .`)
3 - Set the image in the pod spec like the build tag (eg my-image)
4 - Set the [imagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) to Never, otherwise Kubernetes will try to download the image.

**Comment by mediumhust** [comment]
```
eval $(minikube docker-env)
docker build -t admin-test:1.1 .

minikube service min-test-svc --url
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: admin-test
 labels:
   app: admin-test
spec:
 selector:
  matchLabels:
   app: admin-test
 template:
  metadata:
   labels:
    app: admin-test
  spec:
   containers:
   - image: admin-test:1.3
     name: nodejs-api
     imagePullPolicy: Never
     ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: admin-test-svc
spec:
    ports:
    - name: "admin-test"
      targetPort: 3000
      port: 3000
      nodePort: 30253
      protocol: TCP
    selector:
       app: admin-test
    type: NodePort
```
