### DISCUSSION TITLE
[docker compose] kafka ui

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#287] [DevOps]
```yml
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    networks:
      - nw_one
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    networks:
      - nw_one
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafkadata:/var/lib/kafka/data
    restart: always

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - nw_one
    ports:
      - 9001:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - "kafka"
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
```

config.yml
```yml
kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafka:29092
```
