### DISCUSSION TITLE
[docker] context & environment

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#29] [DevOps]
```
version: "3.3"

services:
  cms:
    build:
      context: ../artemis-cms
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www/app
    ports:
      - 1337:1337
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - DATABASE_HOST=mysql_cms
      - DATABASE_PORT=3306
      - DATABASE_NAME=artemis_dev
      - DATABASE_USERNAME=cpadmin@artemis-dev
      - DATABASE_PASSWORD=Jaddlk2021
    depends_on:
      - mysql_cms
    networks:
      - artemis

  community:
    build:
      context: ../artemis-be-comm
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www/app
    ports:
      - 1338:1338
    environment:
      - HOST=0.0.0.0
      - PORT=1338
      
      - DATABASE_HOST=mysql_community
      - DATABASE_PORT=3306
      - DATABASE_NAME=artemis_community
      - DATABASE_USERNAME=cpadmin@artemis-dev
      - DATABASE_PASSWORD=Jaddlk2021
      
      - CMS_DATABASE_HOST=mysql_cms
      - CMS_DATABASE_PORT=3306
      - CMS_DATABASE_NAME=artemis_dev
      - CMS_DATABASE_USERNAME=cpadmin@artemis-dev
      - CMS_DATABASE_PASSWORD=Jaddlk2021
    depends_on:
      - mysql_cms
      - mysql_community
    networks:
      - artemis

  notification:
    build:
      context: ../artemis-notification
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www/app
    ports:
      - 1339:1339
    environment:
      - HOST=0.0.0.0
      - PORT=1339
      - DATABASE_HOST=mysql_notification
      - DATABASE_PORT=3306
      - DATABASE_NAME=artemis_notification
      - DATABASE_USERNAME=cpadmin@artemis-dev
      - DATABASE_PASSWORD=Jaddlk2021
      
      - COMMUNITY_DATABASE_HOST=mysql_community
      - COMMUNITY_DATABASE_PORT=3306
      - COMMUNITY_DATABASE_NAME=artemis_community
      - COMMUNITY_DATABASE_USERNAME=cpadmin@artemis-dev
      - COMMUNITY_DATABASE_PASSWORD=Jaddlk2021
      
      - CMS_DATABASE_HOST=mysql_cms
      - CMS_DATABASE_PORT=3306
      - CMS_DATABASE_NAME=artemis_dev
      - CMS_DATABASE_USERNAME=cpadmin@artemis-dev
      - CMS_DATABASE_PASSWORD=Jaddlk2021
      - ENVIRONMENT=dev
    depends_on:
      - mysql_cms
      - mysql_community
      - mysql_notification
    networks:
      - artemis

  mysql_cms:
    container_name: mysql_cms
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: artemis_dev
      MYSQL_USER: cpadmin@artemis-dev
      MYSQL_PASSWORD: Jaddlk2021
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data/cms/mysql:/var/lib/mysql
      - ./mysql/cms/data:/docker-entrypoint-initdb.d
    networks:
      - artemis

  mysql_community:
    container_name: mysql_community
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: artemis_community
      MYSQL_USER: cpadmin@artemis-dev
      MYSQL_PASSWORD: Jaddlk2021
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./data/community/mysql:/var/lib/mysql
      - ./mysql/community/data:/docker-entrypoint-initdb.d
    networks:
      - artemis

  mysql_notification:
    container_name: mysql_notification
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: artemis_notification
      MYSQL_USER: cpadmin@artemis-dev
      MYSQL_PASSWORD: Jaddlk2021
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ./data/notification/mysql:/var/lib/mysql
      - ./mysql/notification/data:/docker-entrypoint-initdb.d
    networks:
      - artemis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - artemis

networks:
  artemis:
    driver: bridge

```
