### DISCUSSION TITLE
husky

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#292] [Vault]
```
npx husky-init && npm install
npm install --save-dev lint-staged
npm install --save-dev @commitlint/config-conventional @commitlint/cli
npx husky add .husky/commit-msg 'npx --no -- commitlint --edit "$1"'
```

.husky/pre-commit
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --allow-empty
```

.husky/commit-msg
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"
```

.lintstagedrc.json
```
{
  "src/**/*.ts": [
    "prettier --write",
    "eslint --fix"
  ]
}
```

.prettierignore
```
src/**/*.spec.ts
```

.eslintrc.js
```
module.exports = {
...
  ignorePatterns: ['.eslintrc.js', 'src/**/*.spec.ts'],
...
}
```

commitlint.config.js
```
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'chore',
        'style',
        'refactor',
        'ci',
        'test',
        'revert',
        'perf',
        'vercel',
      ],
    ],
  },
};
```

Dockerfile (Disable husky in Docker)
```
FROM node:18.11.0
WORKDIR /app/resource
COPY . .
RUN npm i --ignore-scripts
RUN npm run build
EXPOSE 3000
CMD ["/bin/bash", "-c", "npm run start"]
```

**Comment by mediumhust** [comment]
husky with shell script
```bash
npm install --save-dev husky
npx husky init

cat >> .husky/commit-msg << EOF
#!/bin/bash

branch=$(git branch | grep '*' | sed 's/* //')
message="$(cat $1)"
reservedPattern="(text1|text2)"
if echo $message | grep -iPq $reservedPattern;
then
  echo "---------------------------"
  echo "🚨 Wrong commit message! 😕"
  echo "Please exclude: '$reservedPattern' from your commit message."
  echo "---------------------------"
  echo "Your commit message was:"
  echo $message
  echo "---------------------------"
  exit 1
elif echo $branch | grep -iPq $reservedPattern;
then
  echo "---------------------------"
  echo "🚨 Wrong branch name! 😕"
  echo "Please exclude: '$reservedPattern' from your branch name."
  echo "---------------------------"
  echo "Your branch name is:"
  echo $message
  echo "---------------------------"
  exit 1
else
  echo "------------------------------"
  echo "✅ Commit is valid! 👍"
  echo "------------------------------"
  exit 0
fi
EOF
```

gitlab ci `.gitlab-ci.yml`
```
image: node:18.11.0-alpine

variables:
  HUSKY: 0

stages:
  - hello
  - install
  - build

hello-job:
  stage: hello
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

install_job:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: install
  script:
    - echo "HUSKY is '$HUSKY'"
    - npm install

build_job:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: build
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  before_script:
    - docker info
  script:
    - docker build . -t my-docker-image
    - docker run my-docker-image npm test
```
Dockerfile
```
FROM node:18.11.0
WORKDIR /app/resource
COPY . .
ARG HUSKY=0
RUN npm install --force
RUN npm run build
EXPOSE 3000
CMD ["/bin/bash", "-c", "npm run start"]
```

**Comment by mediumhust** [comment]
#### alternatives: lefthook
`lefthook.yaml`
```yaml
commit-msg:
  commands:
    lint:
      run: |
        echo "Running msg validation\n" && 
        chmod +x ./lint.sh && ./lint.sh
```
`lint.sh`
```bash
#!/bin/bash

branch=$(git branch | grep '*' | sed 's/* //')
echo "Current branch: $branch"

message="$(cat .git/COMMIT_EDITMSG)"
echo "Commit message: $message"

# TODO
```
