### DISCUSSION TITLE
gitlab-ci

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#306] [Vault]
```yaml
stages:
  - build
  - test
  - deploy
  - post deploy

variables:
  APP_VERSION: $CI_PIPELINE_IID

# use dot annotation to disable stage
.temp:
  image: node:16-alpine

build:
  stage: build
  script:
    - yarn install
    - yarn build
    - echo $APP_VERSION > build/version.html
  artifacts:
    paths:
      - build
  extends: .temp

test website:
  image: node:16-alpine
  stage: test
  script:
    - yarn global add serve
    - apk add curl
    # run cmd in background
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"

deploy to s3:
  stage: deploy
  enviroment: production
  image: 
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete

production tests:
  stage: post deploy
  image: curlimages/curl
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $CI_ENVIROMENT_URL | grep "React App"
    - curl $CI_ENVIROMENT_URL/version.html | grep $APP_VERSION

build docker image:
  stage: package
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  script:
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker push --all-tag $CI_REGISTRY_IMAGE

test docker image:
  stage: test
  image: curlimages/curl
  services:
    - name: $CI_REGISTRY_IMAGE:$APP_VERSION
      alias: website
  script:
    - curl http://website/version.html | grep $APP_VERSION

deploy to elasticbeanstalk:
  stage: deploy elasticbeanstalk
  image: 
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  variables:
    APP_NAME: My website
    APP_ENV_NAME: Mywebsite-env
  script:
    - yum install gettext -y
    - export DEPLOY_TOKEN=$(echo $GITLAB_DEPLOY_TOKEN | tr -d "\n" | base64)
    - envsubt < templates/Dockerrun.aws.json > Dockerrun.aws.json
    - envsubt < templates/auth.json > auth.json
    # - cat auth.json
    - aws s3 cp Dockerrun.aws.json s3://$AWS_S3_BUCKET/Dockerrun.aws.json
    - aws s3 cp auth.json s3://$AWS_S3_BUCKET/auth.json
    - aws elasticbeanstalk create-application-version --application-name "$APP_NAME" --version-label $APP_VERSION --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=Dockerrun.aws.json
    - aws elasticbeanstalk update-environment --application-name "$APP_NAME" --version-label $APP_VERSION --environment-name $APP_ENV_NAME
    - aws elasticbeanstalk wait environment-updated --application-name "$APP_NAME" --version-label $APP_VERSION --environment-name $APP_ENV_NAME
    - curl $CI_ENVIRONMENT_URL/version.html | grep $APP_VERSION
```
