### DISCUSSION TITLE
nest metrics - prometheus & grafana

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#341] [DevOps]
REFs:
- https://www.youtube.com/watch?v=2ESOGJTXv1s
- https://github.com/mguay22/nestjs-metrics
- https://github.com/willsoto/nestjs-prometheus
- https://github.com/siimon/prom-client

**Comment by mediumhust** [comment]
```
helm create nestjs-metrics
kubectl create deployment nestjs-metrics --mage=mguay/nestjs-metrics --port 3000 --dry-run=client -o yaml > deployment.yaml
helm dependency update
helm install nestjs-metrics
kubectl get secret nestjs-metrics-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
```

**Comment by mediumhust** [comment]
bin/prometheus.yml
```yml
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "example-nodejs-app"
    static_configs:
      - targets: ["localhost:3001"]
```

bin/datasources.yml
```yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    editable: true
```

bin/prometheus.sh
```sh
#!/bin/bash

echo "Start prometheus..."
docker run --rm -p 9090:9090 --network="host" \
  -v `pwd`/bin/prometheus.yml:/etc/prometheus/prometheus.yml \
  prom/prometheus:v2.20.1
```

bin/grafana.sh
```sh
#!/bin/bash

echo "Start grafana..."
docker run --rm -p 3000:3000 --network="host" \
  -e GF_AUTH_DISABLE_LOGIN_FORM=true \
  -e GF_AUTH_ANONYMOUS_ENABLED=true \
  -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin \
  -v `pwd`/bin/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml \
  grafana/grafana:7.1.5
```
