### DISCUSSION TITLE
docker compose mongo replica

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#347] [DevOps]
docker-compose.yaml
```
version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:7.0
    entrypoint:
      - bash
      - -c
      - |
        cp /auth/local.file.key /auth/file.key
        chmod 400 /auth/file.key
        chown 999:999 /auth/file.key
        exec docker-entrypoint.sh $$@
    command:
      [
        "mongod",
        "--port",
        "27017",
        "--keyFile",
        "/auth/file.key",
        "--replSet",
        "rs0",
        "--bind_ip_all"
      ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: trust-registry
    expose:
      - 27018
    ports:
      - 27018:27017
    networks:
      - ssi-trust-registry
    volumes:
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/local.file.key:/auth/local.file.key
    healthcheck:
      test: echo 'rs.status().ok' | mongosh admin --port 27017 -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 30s
      start_period: 60s
  mongo-replica-setup:
    container_name: mongo-setup
    image: mongo:7.0
    restart: on-failure
    networks:
      - ssi-trust-registry
    volumes:
      - ./.docker/mongodb/scripts:/scripts
    entrypoint: [ "bash", "/scripts/mongo-setup.sh" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    depends_on:
      - mongo
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - ssi-trust-registry
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:

networks:
  ssi-trust-registry:

```
