### DISCUSSION TITLE
k8s - trivy - sonarqube - git actions - prometheus  - grafana - node exporter - blackbox exporter

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#349] [DevOps]
REFs: 
- https://medium.com/@devopsshack/-86bd0b2144c1
- https://www.youtube.com/watch?v=FTrTFOLbdm4
- https://github.com/mediumhust/Boardgame

**Comment by mediumhust** [comment]
create 3 AWS EC2 Ubuntu Server 20.04 LTS instances: master, worker node and runner
```
sudo apt update && sudo apt upgrade -y 
```

**Comment by mediumhust** [comment]
setup.sh
```
sudo apt install docker.io -y
sudo chmod 666 /var/run/docker.sock
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
sudo mkdir -p -m 755 /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg — dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg echo ‘deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /’ | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt update
sudo apt install -y kubeadm=1.28.1-1.1 kubelet=1.28.1-1.1 kubectl=1.28.1-1.1
```
on master and worket node
```
sudo chmod +x setup.sh 
sudo ./setup.sh
```

**Comment by mediumhust** [comment]
init_master.sh
```bash
sudo kubeadm init — pod-network-cidr=10.244.0.0/16
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingressnginx/controller-v0.49.0/deploy/static/provider/baremetal/deploy.yaml
```
```bash
sudo chmod +x init_master.sh 
sudo ./init_master.sh
```

**Comment by mediumhust** [comment]
master
```
kubeadm init
````
Execute the command on the worker node as the root user.

**Comment by mediumhust** [comment]
master

sa.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: githubaction
  namespace: webapps
```

role.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: webapps
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  resources:
  - pods
  - componentstatuses
  - configmaps
  - daemonsets
  - deployments
  - events
  - endpoints
  - horizontalpodautoscalers
  - ingress
  - jobs
  - limitranges
  - namespaces
  - nodes
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - serviceaccounts
  - services
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

rb.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: webapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
- kind: ServiceAccount
  name: githubaction
  namespace: webapps
```

sas.yaml
```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: myserviceaccount
```

get KUBE_CONFIG
```
base64 ~/.kube/config
```
