### DISCUSSION TITLE
docker 101

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#367] [DevOps]
default volumes dir
```
/var/lib/docker/volumes/
```
---
set container auto restart
```
docker run -d -p 8081:8081 -p 8082:8082 --restart=always --name nexus -v nexus-data:/nexus-data sonatype/nexus3
```
---
update `daemon.json` to allow insecure registries
```
cat /etc/docker/deamon/json
```
```
{
  "insecure-registries": ["3.109.108.33:8082","3.109.108.33:8085"]
}
```
```
systemctl restart docker
```
---
## Analyzes image:
- [Docker Scout](https://docs.docker.com/scout/)

**Comment by mediumhust** [comment]
## Use private registry ghcr.io for github action

### Create a Personal Access Token
`GitHub Account > Settings > Developer Settings > Personal Access Tokens`
select options: read/write/delete packages

### Create secrete ( named:  DOCKER_CONTAINER_REGISTRY_TOKEN)
`Settings > Secrets > New Secret`

### Push image to ghcr.io
```
export DOCKER_CONTAINER_REGISTRY_TOKEN=<the personal access token>
# Login to your ghcr.io
echo $DOCKER_CONTAINER_REGISTRY_TOKEN | docker login ghcr.io -u <YOUR_USERNAME> --password-stdin
# As an example, here I pull an image, tag it, and push it.
docker pull ubuntu:18.04
docker tag ubuntu:18.04 ghcr.io/<YOUR_USERNAME>/my_special_ubuntu:latest
docker push ghcr.io/<YOUR_USERNAME>/my_special_ubuntu:latest
```

### Edit github action `super-action.yml`
```
# Action name
name: Super Action

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    super-job:
        runs-on: ubuntu-18.04
        container:
            image: ghcr.io/<YOUR_USERNAME>/<IMAGE_NAME>:<IMAGE_TAG>
            credentials:
               username: <YOUR_USERNAME>
               password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
        steps:
            - name: super-step
              shell: bash
              run: |
                # Whatever commands you want to run here using the container with your
                # new Docker image at ghcr.io!
                echo "--This is running in my custom Docker image--"
```
