### DISCUSSION TITLE
opentelemetry aspecto

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#372] [Vault]
- [aspecto](https://www.aspecto.io/)
- https://opentelemetry.io/docs/demo/kubernetes-deployment/
- https://github.com/open-telemetry/opentelemetry-helm-charts

```
export ASPECTO_KEY='e97ea97d-3df2-4c97-xxxx-xxxxxxxxxxxx'

kubectl create secret generic aspecto-key --from-literal=api-key="$ASPECTO_KEY" -n otel-demo-newrelic

kubectl create ns otel-demo-newrelic
```

**otel-demo-newrelic-values.yaml**
```yml
prometheus:
  enabled: false
opensearch:
  enabled: false
grafana:
  enabled: false
jaeger:
  enabled: false

opentelemetry-collector:
  config:
    exporters:
      otlp/aspecto:
        endpoint: otelcol.aspecto.io:4317
        headers:
          Authorization: ${ASPECTO_KEY}
        tls:
          insecure: false
    service:
      pipelines:
        logs:
          exporters: [otlp/aspecto, debug]
        metrics:
          exporters: [otlp/aspecto, debug]
          receivers: [httpcheck/frontendproxy, redis, otlp]
        traces:
          exporters: [otlp/aspecto, debug]
  extraEnvs:
    - name: ASPECTO_KEY
      valueFrom:
        secretKeyRef:
          key: api-key
          name: aspecto-key
```

**otel-demo-newrelic-helmfile.yaml**
```yml
repositories:
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
- name: otel-demo-newrelic
  chart: open-telemetry/opentelemetry-demo
  namespace: otel-demo-newrelic
  values:
  - otel-demo-newrelic-values.yaml
```

```
helmfile sync -f otel-demo-newrelic-helmfile.yaml
```

```
kubectl port-forward svc/otel-demo-newrelic-frontendproxy 8080:8080 -n otel-demo-newrelic
```

---
### Clear up
```
unset ASPECTO_KEY
helmfile destroy -f otel-demo-newrelic-helmfile.yaml
```
