### DISCUSSION TITLE
github action self-hosted - slack notification

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#377] [DevOps]
Settings –> Actions –> Runners

---

sonar-project.properties
```
sonar.projectKey=myntra
```

.github/workflows/build.yml
```yml
name: Build,Analyze,scan
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: npm install dependency
        run: npm install
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Scout Scan
        run: |
          docker-scout quickview fs://.
          docker-scout cves fs://.
      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build -t myntra .
          docker tag myntra namespace/myntra:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push namespace/myntra:latest
        env:
          DOCKER_CLI_ACI: 1
      - name: Docker Scout Image Scan
        run: |
          docker-scout quickview namespace/myntra:latest
          docker-scout cves namespace/myntra:latest
  deploy:
   needs: build-analyze-scan
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull namespace/myntra:latest
      - name: Deploy to container
        run: docker run -d --name game -p 3000:3000 namespace/myntra:latest
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml
      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubactions-eks'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

deployment-service.yml
```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        image: namespace/myntra:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myntra-service
spec:
  selector:
    app: myntra
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
```
