### DISCUSSION TITLE
docker compose 101

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#381] [DevOps]
join a pre-existing network
```
services:
  # ...
networks:
  network1:
    name: my-pre-existing-network
    external: true
```
