### DISCUSSION TITLE
github action with k8s config

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#384] [DevOps]
REFs: 
- https://github.com/TinyHust/notes/discussions/349
- https://github.com/mediumhust/Boardgame/blob/main/.github/workflows/cicd.yml

**1 - get config**
```
base64 ~/.kube/config
```
or
```
cat $HOME/.kube/config | base64
```

**2 - create actions secret named: KUBE_CONFIG**
![image](https://github.com/user-attachments/assets/b0756498-6c6c-4976-8ac4-31141e43aa67)

**3 - github action job**
```
    - name: Kubectl Action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: |
          kubectl apply -f deployment-service.yaml -n webapps
          kubectl get svc -n webapps
```
