### DISCUSSION TITLE
caddy + wordpress

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#389] [Vault]
```
├── wordpress/
│   ├── html/
│   ├── .env
│   └── compose.yml
└── caddy/
    ├── Caddyfile
    └── compose.yml
```

wordpress/compose.yml
```yml
services:
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file: .env

  db:
    image: mariadb:10.11.6-jammy
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
```

wordpress/.env
```
## MYSQL ##
MYSQL_USER=siteuser
MYSQL_PASSWORD=sitepassword
MYSQL_DATABASE=wordpress
MYSQL_ROOT_PASSWORD=rootpassword
```

caddy/compose.yml
```yml
services:
  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ../wordpress/html:/var/www/html

networks:
  default:
    name: wordpress_default
    external: true
```

Caddyfile
```
domain.com {
	root * /var/www/html
	encode zstd gzip

	# Serve WordPress PHP files through php-fpm:
	php_fastcgi wordpress:9000

	# Enable the static file server:
	file_server {
		precompressed gzip
	}
	header / {
		X-Frame-Options "SAMEORIGIN"
		X-Content-Type-Options "nosniff"
	}

}
```
---
```
docker compose up -d --force-recreate
```
