### DISCUSSION TITLE
portainer minikube

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#390] [DevOps]
docker-compose.yml
```yml
version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    network_mode: host
```

```
kubectl apply -f https://downloads.portainer.io/ce2-19/portainer-agent-k8s-lb.yaml
kubectl port-forward pods/portainer-agent-56b55d4bc6-j95tz -n portainer 9001:9001
```
Environment address: `127.0.0.1:9001`
