### DISCUSSION TITLE
git hook: lefthook eslint

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#393] [DevOps]
lefthook.yml
```yml
pre-commit:
  parallel: true
  commands:
    eslint:
      run: |
        git diff --cached --name-only --diff-filter=ACM | grep '\.ts$' | xargs npx eslint --fix
```
