### DISCUSSION TITLE
jenkins prometheus grafana influxdb

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#409] [DevOps]
REFs:
- https://mrcloudbook.com/secure-aws-eks-with-ssl-and-monitor-using-influxdb-in-devsecops-project/
- https://github.com/mediumhust/ANSIBLE
- https://github.com/mediumhust/two-tier-flask-app
- https://github.com/mediumhust/EKS-OBSERVABILITY
- https://www.youtube.com/watch?v=Q7kYJFNgEmg

**Comment by mediumhust** [comment]
```
docker run -d --name prometheus-container -v /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml -e TZ=UTC -p 9090:9090 ubuntu/prometheus:2.50.0-22.04_stable

docker run -d -p 8086:8086 --name influxdb2 influxdb:1.8.6-alpine
```

```
docker exec -it influxdb2 bash
influx
CREATE DATABASE "jenkins" WITH DURATION 1825d REPLICATION 1 NAME "jenkins-retention"
SHOW DATABASES
USE jenkins
```

**Comment by mediumhust** [comment]
prometheus.yml

```yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["<jenkins-ip>:8080"]
```
