### DISCUSSION TITLE
mongo docker

### DISCUSSION THREAD

**Discussion by mediumhust** [TinyHust/notes#91] [Vault]
```yml
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ddd
```

connect uri:
```
mongodb://root:example@localhost:27017/ddd?authSource=admin
```
